[server][global]

port = 8501developmentMode = false

headless = true

enableCORS = false[server]

enableXsrfProtection = falseheadless = true

port = 8501

[browser]enableCORS = false

gatherUsageStats = falseenableXsrfProtection = false

serverAddress = "0.0.0.0"

[browser]

[theme]gatherUsageStats = false

primaryColor = "#FF6B35"serverAddress = "0.0.0.0"

backgroundColor = "#FFFFFF"

secondaryBackgroundColor = "#F0F2F6"[theme]

textColor = "#262730"primaryColor = "#1f77b4"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
