# Streamlit Secrets Template
# Copy this to secrets.toml and add your actual credentials

[KITE_API]
api_key = "your_kite_api_key_here"
api_secret = "your_kite_api_secret_here" 
access_token = "will_be_updated_daily"

[TRADING]
capital = 500000
demo_mode = false
max_positions = 8
position_size_percent = 3.0

[EMAIL]
smtp_server = "smtp.gmail.com"
smtp_port = 587
email_username = "your_email@gmail.com"
email_password = "your_app_password"